# Generated by Django 3.2 on 2022-12-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
